#!/usr/bin/env node
// Generates pages/gallery-images.js by scanning the images folder.
// Run after adding/removing photos: node scripts/generate-gallery.js
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const IMAGES_DIR = path.join(ROOT, 'images');
const OUT_FILE = path.join(ROOT, 'pages', 'gallery-images.js');

const GALLERY_EXT = /\.(jpe?g|png|gif)$/i;
const EXCLUDE = /(^|\/)(logo\.jpe?g|apostle\.jpe?g|background\.png)$/i;

const files = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else {
      const rel = path.relative(IMAGES_DIR, full).split(path.sep).join('/');
      if (GALLERY_EXT.test(rel) && !EXCLUDE.test(rel)) {
        files.push(rel);
      }
    }
  }
}

if (!fs.existsSync(IMAGES_DIR)) {
  console.error('Images folder not found:', IMAGES_DIR);
  process.exit(1);
}

walk(IMAGES_DIR);
files.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

const content =
  '// Auto-generated by scripts/generate-gallery.js - do not edit manually.\n' +
  '// Regenerate after adding/removing photos: node scripts/generate-gallery.js\n' +
  'window.GALLERY_IMAGES = [\n' +
  files.map(f => '  ' + JSON.stringify('../images/' + f)).join(',\n') +
  '\n];\n';

fs.writeFileSync(OUT_FILE, content);
console.log(`Generated ${files.length} images -> ${path.relative(ROOT, OUT_FILE)}`);
